# Generated by Django 3.2 on 2021-04-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select The Bed Choices'), (1, 'General'), (2, 'SemiPrivate'), (3, 'Private')], null=True)),
                ('bed_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.country')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select The Gender Choices'), (1, 'Male'), (2, 'Female')], null=True)),
                ('patient_status', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select The Patient Choices'), (1, 'Admit'), (2, 'Discharged')], null=True)),
                ('marital_status', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select The Marital Choices'), (1, 'Single'), (2, 'Married')], null=True)),
                ('occupation', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date OF Birth')),
                ('location_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='mobile number')),
                ('address_line1', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line1')),
                ('address_line2', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line2')),
                ('admit_on', models.DateTimeField(blank=True, null=True)),
                ('discharged_on', models.DateTimeField(blank=True, null=True)),
                ('bed_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beds.beds')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.state'),
        ),
    ]
