# Generated by Django 3.2 on 2021-04-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_auto_20210414_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beds.beds', unique=True),
        ),
    ]
