# Generated by Django 3.2 on 2021-04-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_alter_patient_bed_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.beds', unique=True),
        ),
    ]
