# Generated by Django 3.2 on 2021-04-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_alter_patient_bed_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='beds',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.patient'),
        ),
        migrations.AlterField(
            model_name='beds',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='beds',
            unique_together={('id', 'patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='beds',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bed_no',
        ),
    ]
