# Generated by Django 3.2 on 2021-04-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_auto_20210414_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bed_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.beds'),
        ),
        migrations.AlterUniqueTogether(
            name='beds',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='beds',
            name='patient_id',
        ),
    ]
