# Generated by Django 3.2 on 2021-04-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0007_alter_beds_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patient'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bed_number',
        ),
        migrations.AddField(
            model_name='beds',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='WardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.beds')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.patient')),
            ],
            options={
                'verbose_name_plural': 'Wardconfig',
            },
        ),
    ]
