# Generated by Django 3.2 on 2021-04-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0008_auto_20210415_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardconfig',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.patient', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='wardconfig',
            unique_together={('bed', 'patient')},
        ),
    ]
