# Generated by Django 3.2 on 2021-04-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0009_auto_20210415_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardconfig',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beds.patient'),
        ),
    ]
