# Generated by Django 3.2 on 2021-04-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0010_alter_wardconfig_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wardconfig',
            unique_together=set(),
        ),
    ]
