# Generated by Django 3.2 on 2021-04-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0011_alter_wardconfig_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WardConfig',
            new_name='Ward',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='beds',
            name='bed_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
